config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :expenditures
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "incomes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
   belongs_to :categorizable, polymorphic: true
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
	has_one :category, as: :categorizable
	attr_accessor :cat
end

app/models/income.rb
class Income < ApplicationRecord
  has_one :category, as: :categorizable
  attr_accessor :cat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :incomes
  has_many :expenditures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /expenditures
  # GET /expenditures.json
  def index
    @expenditures = current_user.expenditures
  end

  # GET /expenditures/1
  # GET /expenditures/1.json
  def show
  end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
  end

  # GET /expenditures/1/edit
  def edit
    @expenditure.cat = @expenditure.category.title
  end

  # POST /expenditures
  # POST /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @expenditure.save
        Category.create(title: params[:expenditure][:cat], categorizable_type: 'Expenditure', categorizable_id: @expenditure.id)
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully created.' }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :new }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenditures/1
  # PATCH/PUT /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        @expenditure.category.update_attributes!(title: params[:expenditure][:cat])
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1
  # DELETE /expenditures/1.json
  def destroy
    @expenditure.destroy
    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenditure
      @expenditure = Expenditure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expenditure_params
      params.require(:expenditure).permit(:title, :expense, :description)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = current_user.incomes
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
    @income.cat = @income.category.title
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @income.save
        Category.create(title: params[:income][:cat], categorizable_type: 'Income', categorizable_id: @income.id)
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        @income.category.update_attributes!(title: params[:income][:cat])
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:title, :income, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/expenditures/_form.html.erb
<%= form_for(expenditure) do |f| %>
  <% if expenditure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
      <% expenditure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :expense %>
    <%= f.text_field :expense, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :cat, class: "form-control"  %>
  </div>
    <%= f.submit  class: "btn btn-default"%>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Editing Expenditure</h1>

<%= render 'form', expenditure: @expenditure %>

<%= link_to 'Show', @expenditure %> |
<%= link_to 'Back', expenditures_path %>

app/views/expenditures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenditures</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Expense</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenditures.each do |expenditure| %>
      <tr>
        <td><%= expenditure.title %></td>
        <td><%= expenditure.expense %></td>
        <td><%= expenditure.description %></td>
        <td><%= expenditure.category.try(:title) %></td>
        <td><%= link_to 'Show', expenditure %></td>
        <td><%= link_to 'Edit', edit_expenditure_path(expenditure) %></td>
        <td><%= link_to 'Destroy', expenditure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expenditure', new_expenditure_path %>

app/views/expenditures/new.html.erb
<h1>New Expenditure</h1>

<%= render 'form', expenditure: @expenditure %>

<%= link_to 'Back', expenditures_path %>

app/views/expenditures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expenditure.title %>
</p>

<p>
  <strong>Expense:</strong>
  <%= @expenditure.expense %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expenditure.description %>
</p>

<%= link_to 'Edit', edit_expenditure_path(@expenditure) %> |
<%= link_to 'Back', expenditures_path %>

app/views/incomes/_form.html.erb
<%= form_for(income) do |f| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :income %>
    <%= f.text_field :income, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :cat, class: "form-control" %>
  </div>

    <%= f.submit  class: "btn btn-default"%>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incomes</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Income</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.title %></td>
        <td><%= income.income %></td>
        <td><%= income.description %></td>
        <td><%= income.cateogry.try(:title) %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @income.title %>
</p>

<p>
  <strong>Income:</strong>
  <%= @income.income %>
</p>

<p>
  <strong>Description:</strong>
  <%= @income.description %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-inverse navbar-custom">
    <div class="container-fluid">
    <div class="navbar-header">
    <a class="navbar-brand" href="#">Expense</a>
        </div>
    <ul class="nav navbar-nav">
        <li style="color:white; padding-top: 15px;"> <%= link_to 'incomes', incomes_path%></li>
        <li style="color:white; padding-top: 15px;"> <%= link_to 'expenditures', expenditures_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="caret"></span></a>
            <ul class= "dropdown-menu accountmenu">

              <li>&nbsp; &nbsp;Welcome: &nbsp; </li>

              <li>&nbsp; &nbsp;Email: &nbsp;</li>
             
              <li>&nbsp; &nbsp;Role: &nbsp; Admin</li>
            </ul>
          </li>      
             <li><
              <span class="glyphicon glyphicon-log-out"  style="color:white; padding-top: 15px;"> Log out</span>
              </li> 
            <li>
              <span class="glyphicon glyphicon-log-in"  style="color:white; padding-top: 15px;"> Login</span>
            </li>
    </ul>
  </div>
</nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Expense</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>